#ifndef GUARD_CONSTANTS_SPECIES_H
#define GUARD_CONSTANTS_SPECIES_H

#define SPECIES_NONE 0
#define SPECIES_BULBASAUR 1
#define SPECIES_IVYSAUR 2
#define SPECIES_VENUSAUR 3
#define SPECIES_CHARMANDER 4
#define SPECIES_CHARMELEON 5
#define SPECIES_CHARIZARD 6
#define SPECIES_SQUIRTLE 7
#define SPECIES_WARTORTLE 8
#define SPECIES_BLASTOISE 9
#define SPECIES_CATERPIE 10
#define SPECIES_METAPOD 11
#define SPECIES_BUTTERFREE 12
#define SPECIES_WEEDLE 13
#define SPECIES_KAKUNA 14
#define SPECIES_BEEDRILL 15
#define SPECIES_PIDGEY 16
#define SPECIES_PIDGEOTTO 17
#define SPECIES_PIDGEOT 18
#define SPECIES_RATTATA 19
#define SPECIES_RATICATE 20
#define SPECIES_SPEAROW 21
#define SPECIES_FEAROW 22
#define SPECIES_EKANS 23
#define SPECIES_ARBOK 24
#define SPECIES_PIKACHU 25
#define SPECIES_RAICHU 26
#define SPECIES_SANDSHREW 27
#define SPECIES_SANDSLASH 28
#define SPECIES_NIDORAN_F 29
#define SPECIES_NIDORINA 30
#define SPECIES_NIDOQUEEN 31
#define SPECIES_NIDORAN_M 32
#define SPECIES_NIDORINO 33
#define SPECIES_NIDOKING 34
#define SPECIES_CLEFAIRY 35
#define SPECIES_CLEFABLE 36
#define SPECIES_VULPIX 37
#define SPECIES_NINETALES 38
#define SPECIES_JIGGLYPUFF 39
#define SPECIES_WIGGLYTUFF 40
#define SPECIES_ZUBAT 41
#define SPECIES_GOLBAT 42
#define SPECIES_ODDISH 43
#define SPECIES_GLOOM 44
#define SPECIES_VILEPLUME 45
#define SPECIES_PARAS 46
#define SPECIES_PARASECT 47
#define SPECIES_VENONAT 48
#define SPECIES_VENOMOTH 49
#define SPECIES_DIGLETT 50
#define SPECIES_DUGTRIO 51
#define SPECIES_MEOWTH 52
#define SPECIES_PERSIAN 53
#define SPECIES_PSYDUCK 54
#define SPECIES_GOLDUCK 55
#define SPECIES_MANKEY 56
#define SPECIES_PRIMEAPE 57
#define SPECIES_GROWLITHE 58
#define SPECIES_ARCANINE 59
#define SPECIES_POLIWAG 60
#define SPECIES_POLIWHIRL 61
#define SPECIES_POLIWRATH 62
#define SPECIES_ABRA 63
#define SPECIES_KADABRA 64
#define SPECIES_ALAKAZAM 65
#define SPECIES_MACHOP 66
#define SPECIES_MACHOKE 67
#define SPECIES_MACHAMP 68
#define SPECIES_BELLSPROUT 69
#define SPECIES_WEEPINBELL 70
#define SPECIES_VICTREEBEL 71
#define SPECIES_TENTACOOL 72
#define SPECIES_TENTACRUEL 73
#define SPECIES_GEODUDE 74
#define SPECIES_GRAVELER 75
#define SPECIES_GOLEM 76
#define SPECIES_PONYTA 77
#define SPECIES_RAPIDASH 78
#define SPECIES_SLOWPOKE 79
#define SPECIES_SLOWBRO 80
#define SPECIES_MAGNEMITE 81
#define SPECIES_MAGNETON 82
#define SPECIES_FARFETCHD 83
#define SPECIES_DODUO 84
#define SPECIES_DODRIO 85
#define SPECIES_SEEL 86
#define SPECIES_DEWGONG 87
#define SPECIES_GRIMER 88
#define SPECIES_MUK 89
#define SPECIES_SHELLDER 90
#define SPECIES_CLOYSTER 91
#define SPECIES_GASTLY 92
#define SPECIES_HAUNTER 93
#define SPECIES_GENGAR 94
#define SPECIES_ONIX 95
#define SPECIES_DROWZEE 96
#define SPECIES_HYPNO 97
#define SPECIES_KRABBY 98
#define SPECIES_KINGLER 99
#define SPECIES_VOLTORB 100
#define SPECIES_ELECTRODE 101
#define SPECIES_EXEGGCUTE 102
#define SPECIES_EXEGGUTOR 103
#define SPECIES_CUBONE 104
#define SPECIES_MAROWAK 105
#define SPECIES_HITMONLEE 106
#define SPECIES_HITMONCHAN 107
#define SPECIES_LICKITUNG 108
#define SPECIES_KOFFING 109
#define SPECIES_WEEZING 110
#define SPECIES_RHYHORN 111
#define SPECIES_RHYDON 112
#define SPECIES_CHANSEY 113
#define SPECIES_TANGELA 114
#define SPECIES_KANGASKHAN 115
#define SPECIES_HORSEA 116
#define SPECIES_SEADRA 117
#define SPECIES_GOLDEEN 118
#define SPECIES_SEAKING 119
#define SPECIES_STARYU 120
#define SPECIES_STARMIE 121
#define SPECIES_MR_MIME 122
#define SPECIES_SCYTHER 123
#define SPECIES_JYNX 124
#define SPECIES_ELECTABUZZ 125
#define SPECIES_MAGMAR 126
#define SPECIES_PINSIR 127
#define SPECIES_TAUROS 128
#define SPECIES_MAGIKARP 129
#define SPECIES_GYARADOS 130
#define SPECIES_LAPRAS 131
#define SPECIES_DITTO 132
#define SPECIES_EEVEE 133
#define SPECIES_VAPOREON 134
#define SPECIES_JOLTEON 135
#define SPECIES_FLAREON 136
#define SPECIES_PORYGON 137
#define SPECIES_OMANYTE 138
#define SPECIES_OMASTAR 139
#define SPECIES_KABUTO 140
#define SPECIES_KABUTOPS 141
#define SPECIES_AERODACTYL 142
#define SPECIES_SNORLAX 143
#define SPECIES_ARTICUNO 144
#define SPECIES_ZAPDOS 145
#define SPECIES_MOLTRES 146
#define SPECIES_DRATINI 147
#define SPECIES_DRAGONAIR 148
#define SPECIES_DRAGONITE 149
#define SPECIES_MEWTWO 150
#define SPECIES_MEW 151
#define SPECIES_CHIKORITA 152
#define SPECIES_BAYLEEF 153
#define SPECIES_MEGANIUM 154
#define SPECIES_CYNDAQUIL 155
#define SPECIES_QUILAVA 156
#define SPECIES_TYPHLOSION 157
#define SPECIES_TOTODILE 158
#define SPECIES_CROCONAW 159
#define SPECIES_FERALIGATR 160
#define SPECIES_SENTRET 161
#define SPECIES_FURRET 162
#define SPECIES_HOOTHOOT 163
#define SPECIES_NOCTOWL 164
#define SPECIES_LEDYBA 165
#define SPECIES_LEDIAN 166
#define SPECIES_SPINARAK 167
#define SPECIES_ARIADOS 168
#define SPECIES_CROBAT 169
#define SPECIES_CHINCHOU 170
#define SPECIES_LANTURN 171
#define SPECIES_PICHU 172
#define SPECIES_CLEFFA 173
#define SPECIES_IGGLYBUFF 174
#define SPECIES_TOGEPI 175
#define SPECIES_TOGETIC 176
#define SPECIES_NATU 177
#define SPECIES_XATU 178
#define SPECIES_MAREEP 179
#define SPECIES_FLAAFFY 180
#define SPECIES_AMPHAROS 181
#define SPECIES_BELLOSSOM 182
#define SPECIES_MARILL 183
#define SPECIES_AZUMARILL 184
#define SPECIES_SUDOWOODO 185
#define SPECIES_POLITOED 186
#define SPECIES_HOPPIP 187
#define SPECIES_SKIPLOOM 188
#define SPECIES_JUMPLUFF 189
#define SPECIES_AIPOM 190
#define SPECIES_SUNKERN 191
#define SPECIES_SUNFLORA 192
#define SPECIES_YANMA 193
#define SPECIES_WOOPER 194
#define SPECIES_QUAGSIRE 195
#define SPECIES_ESPEON 196
#define SPECIES_UMBREON 197
#define SPECIES_MURKROW 198
#define SPECIES_SLOWKING 199
#define SPECIES_MISDREAVUS 200
#define SPECIES_UNOWN 201
#define SPECIES_WOBBUFFET 202
#define SPECIES_GIRAFARIG 203
#define SPECIES_PINECO 204
#define SPECIES_FORRETRESS 205
#define SPECIES_DUNSPARCE 206
#define SPECIES_GLIGAR 207
#define SPECIES_STEELIX 208
#define SPECIES_SNUBBULL 209
#define SPECIES_GRANBULL 210
#define SPECIES_QWILFISH 211
#define SPECIES_SCIZOR 212
#define SPECIES_SHUCKLE 213
#define SPECIES_HERACROSS 214
#define SPECIES_SNEASEL 215
#define SPECIES_TEDDIURSA 216
#define SPECIES_URSARING 217
#define SPECIES_SLUGMA 218
#define SPECIES_MAGCARGO 219
#define SPECIES_SWINUB 220
#define SPECIES_PILOSWINE 221
#define SPECIES_CORSOLA 222
#define SPECIES_REMORAID 223
#define SPECIES_OCTILLERY 224
#define SPECIES_DELIBIRD 225
#define SPECIES_MANTINE 226
#define SPECIES_SKARMORY 227
#define SPECIES_HOUNDOUR 228
#define SPECIES_HOUNDOOM 229
#define SPECIES_KINGDRA 230
#define SPECIES_PHANPY 231
#define SPECIES_DONPHAN 232
#define SPECIES_PORYGON2 233
#define SPECIES_STANTLER 234
#define SPECIES_SMEARGLE 235
#define SPECIES_TYROGUE 236
#define SPECIES_HITMONTOP 237
#define SPECIES_SMOOCHUM 238
#define SPECIES_ELEKID 239
#define SPECIES_MAGBY 240
#define SPECIES_MILTANK 241
#define SPECIES_BLISSEY 242
#define SPECIES_RAIKOU 243
#define SPECIES_ENTEI 244
#define SPECIES_SUICUNE 245
#define SPECIES_LARVITAR 246
#define SPECIES_PUPITAR 247
#define SPECIES_TYRANITAR 248
#define SPECIES_LUGIA 249
#define SPECIES_HO_OH 250
#define SPECIES_CELEBI 251

#define SPECIES_OLD_UNOWN_B 252
#define SPECIES_OLD_UNOWN_C 253
#define SPECIES_OLD_UNOWN_D 254
#define SPECIES_OLD_UNOWN_E 255
#define SPECIES_OLD_UNOWN_F 256
#define SPECIES_OLD_UNOWN_G 257
#define SPECIES_OLD_UNOWN_H 258
#define SPECIES_OLD_UNOWN_I 259
#define SPECIES_OLD_UNOWN_J 260
#define SPECIES_OLD_UNOWN_K 261
#define SPECIES_OLD_UNOWN_L 262
#define SPECIES_OLD_UNOWN_M 263
#define SPECIES_OLD_UNOWN_N 264
#define SPECIES_OLD_UNOWN_O 265
#define SPECIES_OLD_UNOWN_P 266
#define SPECIES_OLD_UNOWN_Q 267
#define SPECIES_OLD_UNOWN_R 268
#define SPECIES_OLD_UNOWN_S 269
#define SPECIES_OLD_UNOWN_T 270
#define SPECIES_OLD_UNOWN_U 271
#define SPECIES_OLD_UNOWN_V 272
#define SPECIES_OLD_UNOWN_W 273
#define SPECIES_OLD_UNOWN_X 274
#define SPECIES_OLD_UNOWN_Y 275
#define SPECIES_OLD_UNOWN_Z 276

<<<<<<< Updated upstream
#define SPECIES_TREECKO 277
#define SPECIES_GROVYLE 278
#define SPECIES_SCEPTILE 279
#define SPECIES_TORCHIC 280
#define SPECIES_COMBUSKEN 281
#define SPECIES_BLAZIKEN 282
#define SPECIES_MUDKIP 283
#define SPECIES_MARSHTOMP 284
#define SPECIES_SWAMPERT 285
#define SPECIES_POOCHYENA 286
#define SPECIES_MIGHTYENA 287
#define SPECIES_ZIGZAGOON 288
#define SPECIES_LINOONE 289
#define SPECIES_WURMPLE 290
#define SPECIES_SILCOON 291
#define SPECIES_BEAUTIFLY 292
#define SPECIES_CASCOON 293
#define SPECIES_DUSTOX 294
#define SPECIES_LOTAD 295
#define SPECIES_LOMBRE 296
#define SPECIES_LUDICOLO 297
#define SPECIES_SEEDOT 298
#define SPECIES_NUZLEAF 299
#define SPECIES_SHIFTRY 300
#define SPECIES_NINCADA 301
#define SPECIES_NINJASK 302
#define SPECIES_SHEDINJA 303
#define SPECIES_TAILLOW 304
#define SPECIES_SWELLOW 305
#define SPECIES_SHROOMISH 306
#define SPECIES_BRELOOM 307
#define SPECIES_SPINDA 308
#define SPECIES_WINGULL 309
#define SPECIES_PELIPPER 310
#define SPECIES_SURSKIT 311
#define SPECIES_MASQUERAIN 312
#define SPECIES_WAILMER 313
#define SPECIES_WAILORD 314
#define SPECIES_SKITTY 315
#define SPECIES_DELCATTY 316
#define SPECIES_KECLEON 317
#define SPECIES_BALTOY 318
#define SPECIES_CLAYDOL 319
#define SPECIES_NOSEPASS 320
#define SPECIES_TORKOAL 321
#define SPECIES_SABLEYE 322
#define SPECIES_BARBOACH 323
#define SPECIES_WHISCASH 324
#define SPECIES_LUVDISC 325
#define SPECIES_CORPHISH 326
#define SPECIES_CRAWDAUNT 327
#define SPECIES_FEEBAS 328
#define SPECIES_MILOTIC 329
#define SPECIES_CARVANHA 330
#define SPECIES_SHARPEDO 331
#define SPECIES_TRAPINCH 332
#define SPECIES_VIBRAVA 333
#define SPECIES_FLYGON 334
#define SPECIES_MAKUHITA 335
#define SPECIES_HARIYAMA 336
#define SPECIES_ELECTRIKE 337
#define SPECIES_MANECTRIC 338
#define SPECIES_NUMEL 339
#define SPECIES_CAMERUPT 340
#define SPECIES_SPHEAL 341
#define SPECIES_SEALEO 342
#define SPECIES_WALREIN 343
#define SPECIES_CACNEA 344
#define SPECIES_CACTURNE 345
#define SPECIES_SNORUNT 346
#define SPECIES_GLALIE 347
#define SPECIES_LUNATONE 348
#define SPECIES_SOLROCK 349
#define SPECIES_AZURILL 350
#define SPECIES_SPOINK 351
#define SPECIES_GRUMPIG 352
#define SPECIES_PLUSLE 353
#define SPECIES_MINUN 354
#define SPECIES_MAWILE 355
#define SPECIES_MEDITITE 356
#define SPECIES_MEDICHAM 357
#define SPECIES_SWABLU 358
#define SPECIES_ALTARIA 359
#define SPECIES_WYNAUT 360
#define SPECIES_DUSKULL 361
#define SPECIES_DUSCLOPS 362
#define SPECIES_ROSELIA 363
#define SPECIES_SLAKOTH 364
#define SPECIES_VIGOROTH 365
#define SPECIES_SLAKING 366
#define SPECIES_GULPIN 367
#define SPECIES_SWALOT 368
#define SPECIES_TROPIUS 369
#define SPECIES_WHISMUR 370
#define SPECIES_LOUDRED 371
#define SPECIES_EXPLOUD 372
#define SPECIES_CLAMPERL 373
#define SPECIES_HUNTAIL 374
#define SPECIES_GOREBYSS 375
#define SPECIES_ABSOL 376
#define SPECIES_SHUPPET 377
#define SPECIES_BANETTE 378
#define SPECIES_SEVIPER 379
#define SPECIES_ZANGOOSE 380
#define SPECIES_RELICANTH 381
#define SPECIES_ARON 382
#define SPECIES_LAIRON 383
#define SPECIES_AGGRON 384
#define SPECIES_CASTFORM 385
#define SPECIES_VOLBEAT 386
#define SPECIES_ILLUMISE 387
#define SPECIES_LILEEP 388
#define SPECIES_CRADILY 389
#define SPECIES_ANORITH 390
#define SPECIES_ARMALDO 391
#define SPECIES_RALTS 392
#define SPECIES_KIRLIA 393
#define SPECIES_GARDEVOIR 394
#define SPECIES_BAGON 395
#define SPECIES_SHELGON 396
#define SPECIES_SALAMENCE 397
#define SPECIES_BELDUM 398
#define SPECIES_METANG 399
#define SPECIES_METAGROSS 400
#define SPECIES_REGIROCK 401
#define SPECIES_REGICE 402
#define SPECIES_REGISTEEL 403
#define SPECIES_KYOGRE 404
#define SPECIES_GROUDON 405
#define SPECIES_RAYQUAZA 406
#define SPECIES_LATIAS 407
#define SPECIES_LATIOS 408
#define SPECIES_JIRACHI 409
#define SPECIES_DEOXYS 410
#define SPECIES_CHIMECHO 411
#define SPECIES_EGG 412
=======
//Hisuian Forms
#define SPECIES_GROWLITHE_HISUI                         993
#define SPECIES_ARCANINE_HISUI                          994
#define SPECIES_VOLTORB_HISUI                           995
#define SPECIES_ELECTRODE_HISUI                         996
#define SPECIES_TYPHLOSION_HISUI                        997
#define SPECIES_QWILFISH_HISUI                          998
#define SPECIES_SNEASEL_HISUI                           999
#define SPECIES_SAMUROTT_HISUI                          1000
#define SPECIES_LILLIGANT_HISUI                         1001
#define SPECIES_ZORUA_HISUI                             1002
#define SPECIES_ZOROARK_HISUI                           1003
#define SPECIES_BRAVIARY_HISUI                          1004
#define SPECIES_SLIGGOO_HISUI                           1005
#define SPECIES_GOODRA_HISUI                            1006
#define SPECIES_AVALUGG_HISUI                           1007
#define SPECIES_DECIDUEYE_HISUI                         1008

// Misc Forms
#define SPECIES_PIKACHU_COSPLAY                         1009
#define SPECIES_PIKACHU_ROCK_STAR                       1010
#define SPECIES_PIKACHU_BELLE                           1011
#define SPECIES_PIKACHU_POP_STAR                        1012
#define SPECIES_PIKACHU_PHD                             1013
#define SPECIES_PIKACHU_LIBRE                           1014
#define SPECIES_PIKACHU_ORIGINAL                        1015
#define SPECIES_PIKACHU_HOENN                           1016
#define SPECIES_PIKACHU_SINNOH                          1017
#define SPECIES_PIKACHU_UNOVA                           1018
#define SPECIES_PIKACHU_KALOS                           1019
#define SPECIES_PIKACHU_ALOLA                           1020
#define SPECIES_PIKACHU_PARTNER                         1021
#define SPECIES_PIKACHU_WORLD                           1022
#define SPECIES_PICHU_SPIKY_EARED                       1023
#define SPECIES_UNOWN_B                                 1024
#define SPECIES_UNOWN_C                                 1025
#define SPECIES_UNOWN_D                                 1026
#define SPECIES_UNOWN_E                                 1027
#define SPECIES_UNOWN_F                                 1028
#define SPECIES_UNOWN_G                                 1029
#define SPECIES_UNOWN_H                                 1030
#define SPECIES_UNOWN_I                                 1031
#define SPECIES_UNOWN_J                                 1032
#define SPECIES_UNOWN_K                                 1033
#define SPECIES_UNOWN_L                                 1034
#define SPECIES_UNOWN_M                                 1035
#define SPECIES_UNOWN_N                                 1036
#define SPECIES_UNOWN_O                                 1037
#define SPECIES_UNOWN_P                                 1038
#define SPECIES_UNOWN_Q                                 1039
#define SPECIES_UNOWN_R                                 1040
#define SPECIES_UNOWN_S                                 1041
#define SPECIES_UNOWN_T                                 1042
#define SPECIES_UNOWN_U                                 1043
#define SPECIES_UNOWN_V                                 1044
#define SPECIES_UNOWN_W                                 1045
#define SPECIES_UNOWN_X                                 1046
#define SPECIES_UNOWN_Y                                 1047
#define SPECIES_UNOWN_Z                                 1048
#define SPECIES_UNOWN_EXCLAMATION                       1049
#define SPECIES_UNOWN_QUESTION                          1050
#define SPECIES_CASTFORM_SUNNY                          1051
#define SPECIES_CASTFORM_RAINY                          1052
#define SPECIES_CASTFORM_SNOWY                          1053
#define SPECIES_DEOXYS_ATTACK                           1054
#define SPECIES_DEOXYS_DEFENSE                          1055
#define SPECIES_DEOXYS_SPEED                            1056
#define SPECIES_BURMY_SANDY                             1057
#define SPECIES_BURMY_TRASH                             1058
#define SPECIES_WORMADAM_SANDY                          1059
#define SPECIES_WORMADAM_TRASH                          1060
#define SPECIES_CHERRIM_SUNSHINE                        1061
#define SPECIES_SHELLOS_EAST                            1062
#define SPECIES_GASTRODON_EAST                          1063
#define SPECIES_ROTOM_HEAT                              1064
#define SPECIES_ROTOM_WASH                              1065
#define SPECIES_ROTOM_FROST                             1066
#define SPECIES_ROTOM_FAN                               1067
#define SPECIES_ROTOM_MOW                               1068
#define SPECIES_DIALGA_ORIGIN                           1069
#define SPECIES_PALKIA_ORIGIN                           1070
#define SPECIES_GIRATINA_ORIGIN                         1071
#define SPECIES_SHAYMIN_SKY                             1072
#define SPECIES_ARCEUS_FIGHTING                         1073
#define SPECIES_ARCEUS_FLYING                           1074
#define SPECIES_ARCEUS_POISON                           1075
#define SPECIES_ARCEUS_GROUND                           1076
#define SPECIES_ARCEUS_ROCK                             1077
#define SPECIES_ARCEUS_BUG                              1078
#define SPECIES_ARCEUS_GHOST                            1079
#define SPECIES_ARCEUS_STEEL                            1080
#define SPECIES_ARCEUS_FIRE                             1081
#define SPECIES_ARCEUS_WATER                            1082
#define SPECIES_ARCEUS_GRASS                            1083
#define SPECIES_ARCEUS_ELECTRIC                         1084
#define SPECIES_ARCEUS_PSYCHIC                          1085
#define SPECIES_ARCEUS_ICE                              1086
#define SPECIES_ARCEUS_DRAGON                           1087
#define SPECIES_ARCEUS_DARK                             1088
#define SPECIES_ARCEUS_FAIRY                            1089
#define SPECIES_BASCULIN_BLUE_STRIPED                   1090
#define SPECIES_BASCULIN_WHITE_STRIPED                  1091
#define SPECIES_DARMANITAN_ZEN                          1092
#define SPECIES_DARMANITAN_GALAR_ZEN                    1093
#define SPECIES_DEERLING_SUMMER                         1094
#define SPECIES_DEERLING_AUTUMN                         1095
#define SPECIES_DEERLING_WINTER                         1096
#define SPECIES_SAWSBUCK_SUMMER                         1097
#define SPECIES_SAWSBUCK_AUTUMN                         1098
#define SPECIES_SAWSBUCK_WINTER                         1099
#define SPECIES_TORNADUS_THERIAN                        1100
#define SPECIES_THUNDURUS_THERIAN                       1101
#define SPECIES_LANDORUS_THERIAN                        1102
#define SPECIES_ENAMORUS_THERIAN                        1103
#define SPECIES_KYUREM_WHITE                            1104
#define SPECIES_KYUREM_BLACK                            1105
#define SPECIES_KELDEO_RESOLUTE                         1106
#define SPECIES_MELOETTA_PIROUETTE                      1107
#define SPECIES_GENESECT_DOUSE                          1108
#define SPECIES_GENESECT_SHOCK                          1109
#define SPECIES_GENESECT_BURN                           1110
#define SPECIES_GENESECT_CHILL                          1111
#define SPECIES_GRENINJA_BOND                           1112
#define SPECIES_GRENINJA_BATTLE_BOND                    SPECIES_GRENINJA_BOND
#define SPECIES_GRENINJA_ASH                            1113
#define SPECIES_VIVILLON_POLAR                          1114
#define SPECIES_VIVILLON_TUNDRA                         1115
#define SPECIES_VIVILLON_CONTINENTAL                    1116
#define SPECIES_VIVILLON_GARDEN                         1117
#define SPECIES_VIVILLON_ELEGANT                        1118
#define SPECIES_VIVILLON_MEADOW                         1119
#define SPECIES_VIVILLON_MODERN                         1120
#define SPECIES_VIVILLON_MARINE                         1121
#define SPECIES_VIVILLON_ARCHIPELAGO                    1122
#define SPECIES_VIVILLON_HIGH_PLAINS                    1123
#define SPECIES_VIVILLON_SANDSTORM                      1124
#define SPECIES_VIVILLON_RIVER                          1125
#define SPECIES_VIVILLON_MONSOON                        1126
#define SPECIES_VIVILLON_SAVANNA                        1127
#define SPECIES_VIVILLON_SUN                            1128
#define SPECIES_VIVILLON_OCEAN                          1129
#define SPECIES_VIVILLON_JUNGLE                         1130
#define SPECIES_VIVILLON_FANCY                          1131
#define SPECIES_VIVILLON_POKEBALL                       1132
#define SPECIES_FLABEBE_YELLOW                          1133
#define SPECIES_FLABEBE_ORANGE                          1134
#define SPECIES_FLABEBE_BLUE                            1135
#define SPECIES_FLABEBE_WHITE                           1136
#define SPECIES_FLOETTE_YELLOW                          1137
#define SPECIES_FLOETTE_ORANGE                          1138
#define SPECIES_FLOETTE_BLUE                            1139
#define SPECIES_FLOETTE_WHITE                           1140
#define SPECIES_FLOETTE_ETERNAL                         1141
#define SPECIES_FLORGES_YELLOW                          1142
#define SPECIES_FLORGES_ORANGE                          1143
#define SPECIES_FLORGES_BLUE                            1144
#define SPECIES_FLORGES_WHITE                           1145
#define SPECIES_FURFROU_HEART_TRIM                      1146
#define SPECIES_FURFROU_STAR_TRIM                       1147
#define SPECIES_FURFROU_DIAMOND_TRIM                    1148
#define SPECIES_FURFROU_DEBUTANTE_TRIM                  1149
#define SPECIES_FURFROU_MATRON_TRIM                     1150
#define SPECIES_FURFROU_DANDY_TRIM                      1151
#define SPECIES_FURFROU_LA_REINE_TRIM                   1152
#define SPECIES_FURFROU_KABUKI_TRIM                     1153
#define SPECIES_FURFROU_PHARAOH_TRIM                    1154
#define SPECIES_MEOWSTIC_F                              1155
#define SPECIES_AEGISLASH_BLADE                         1156
#define SPECIES_PUMPKABOO_SMALL                         1157
#define SPECIES_PUMPKABOO_LARGE                         1158
#define SPECIES_PUMPKABOO_SUPER                         1159
#define SPECIES_GOURGEIST_SMALL                         1160
#define SPECIES_GOURGEIST_LARGE                         1161
#define SPECIES_GOURGEIST_SUPER                         1162
#define SPECIES_XERNEAS_ACTIVE                          1163
#define SPECIES_ZYGARDE_10                              SPECIES_ZYGARDE_10_AURA_BREAK
#define SPECIES_ZYGARDE_10_AURA_BREAK                   1164
#define SPECIES_ZYGARDE_10_POWER_CONSTRUCT              1165
#define SPECIES_ZYGARDE_50_POWER_CONSTRUCT              1166
#define SPECIES_ZYGARDE_COMPLETE                        1167
#define SPECIES_HOOPA_UNBOUND                           1168
#define SPECIES_ORICORIO_POM_POM                        1169
#define SPECIES_ORICORIO_PAU                            1170
#define SPECIES_ORICORIO_SENSU                          1171
#define SPECIES_ROCKRUFF_OWN_TEMPO                      1172
#define SPECIES_LYCANROC_MIDNIGHT                       1173
#define SPECIES_LYCANROC_DUSK                           1174
#define SPECIES_WISHIWASHI_SCHOOL                       1175
#define SPECIES_SILVALLY_FIGHTING                       1176
#define SPECIES_SILVALLY_FLYING                         1177
#define SPECIES_SILVALLY_POISON                         1178
#define SPECIES_SILVALLY_GROUND                         1179
#define SPECIES_SILVALLY_ROCK                           1180
#define SPECIES_SILVALLY_BUG                            1181
#define SPECIES_SILVALLY_GHOST                          1182
#define SPECIES_SILVALLY_STEEL                          1183
#define SPECIES_SILVALLY_FIRE                           1184
#define SPECIES_SILVALLY_WATER                          1185
#define SPECIES_SILVALLY_GRASS                          1186
#define SPECIES_SILVALLY_ELECTRIC                       1187
#define SPECIES_SILVALLY_PSYCHIC                        1188
#define SPECIES_SILVALLY_ICE                            1189
#define SPECIES_SILVALLY_DRAGON                         1190
#define SPECIES_SILVALLY_DARK                           1191
#define SPECIES_SILVALLY_FAIRY                          1192
#define SPECIES_MINIOR_ORANGE                           SPECIES_MINIOR_METEOR_ORANGE
#define SPECIES_MINIOR_YELLOW                           SPECIES_MINIOR_METEOR_YELLOW
#define SPECIES_MINIOR_GREEN                            SPECIES_MINIOR_METEOR_GREEN
#define SPECIES_MINIOR_BLUE                             SPECIES_MINIOR_METEOR_BLUE
#define SPECIES_MINIOR_INDIGO                           SPECIES_MINIOR_METEOR_INDIGO
#define SPECIES_MINIOR_VIOLET                           SPECIES_MINIOR_METEOR_VIOLET
#define SPECIES_MINIOR_METEOR_ORANGE                    1193
#define SPECIES_MINIOR_METEOR_YELLOW                    1194
#define SPECIES_MINIOR_METEOR_GREEN                     1195
#define SPECIES_MINIOR_METEOR_BLUE                      1196
#define SPECIES_MINIOR_METEOR_INDIGO                    1197
#define SPECIES_MINIOR_METEOR_VIOLET                    1198
#define SPECIES_MINIOR_CORE                             SPECIES_MINIOR_CORE_RED
#define SPECIES_MINIOR_CORE_RED                         1199
#define SPECIES_MINIOR_CORE_ORANGE                      1200
#define SPECIES_MINIOR_CORE_YELLOW                      1201
#define SPECIES_MINIOR_CORE_GREEN                       1202
#define SPECIES_MINIOR_CORE_BLUE                        1203
#define SPECIES_MINIOR_CORE_INDIGO                      1204
#define SPECIES_MINIOR_CORE_VIOLET                      1205
#define SPECIES_MIMIKYU_BUSTED                          1206
#define SPECIES_NECROZMA_DUSK_MANE                      1207
#define SPECIES_NECROZMA_DAWN_WINGS                     1208
#define SPECIES_NECROZMA_ULTRA                          1209
#define SPECIES_MAGEARNA_ORIGINAL                       1210
#define SPECIES_CRAMORANT_GULPING                       1211
#define SPECIES_CRAMORANT_GORGING                       1212
#define SPECIES_TOXTRICITY_LOW_KEY                      1213
#define SPECIES_SINISTEA_ANTIQUE                        1214
#define SPECIES_POLTEAGEIST_ANTIQUE                     1215
#define SPECIES_ALCREMIE_RUBY_CREAM                     SPECIES_ALCREMIE_STRAWBERRY_RUBY_CREAM
#define SPECIES_ALCREMIE_MATCHA_CREAM                   SPECIES_ALCREMIE_STRAWBERRY_MATCHA_CREAM
#define SPECIES_ALCREMIE_MINT_CREAM                     SPECIES_ALCREMIE_STRAWBERRY_MINT_CREAM
#define SPECIES_ALCREMIE_LEMON_CREAM                    SPECIES_ALCREMIE_STRAWBERRY_LEMON_CREAM
#define SPECIES_ALCREMIE_SALTED_CREAM                   SPECIES_ALCREMIE_STRAWBERRY_SALTED_CREAM
#define SPECIES_ALCREMIE_RUBY_SWIRL                     SPECIES_ALCREMIE_STRAWBERRY_RUBY_SWIRL
#define SPECIES_ALCREMIE_CARAMEL_SWIRL                  SPECIES_ALCREMIE_STRAWBERRY_CARAMEL_SWIRL
#define SPECIES_ALCREMIE_RAINBOW_SWIRL                  SPECIES_ALCREMIE_STRAWBERRY_RAINBOW_SWIRL
#define SPECIES_ALCREMIE_STRAWBERRY_RUBY_CREAM          1216
#define SPECIES_ALCREMIE_STRAWBERRY_MATCHA_CREAM        1217
#define SPECIES_ALCREMIE_STRAWBERRY_MINT_CREAM          1218
#define SPECIES_ALCREMIE_STRAWBERRY_LEMON_CREAM         1219
#define SPECIES_ALCREMIE_STRAWBERRY_SALTED_CREAM        1220
#define SPECIES_ALCREMIE_STRAWBERRY_RUBY_SWIRL          1221
#define SPECIES_ALCREMIE_STRAWBERRY_CARAMEL_SWIRL       1222
#define SPECIES_ALCREMIE_STRAWBERRY_RAINBOW_SWIRL       1223
#define SPECIES_EISCUE_NOICE                            1224
#define SPECIES_INDEEDEE_F                              1225
#define SPECIES_MORPEKO_HANGRY                          1226
#define SPECIES_ZACIAN_CROWNED                          1227
#define SPECIES_ZAMAZENTA_CROWNED                       1228
#define SPECIES_ETERNATUS_ETERNAMAX                     1229
#define SPECIES_URSHIFU_RAPID_STRIKE                    1230
#define SPECIES_ZARUDE_DADA                             1231
#define SPECIES_CALYREX_ICE                             1232
#define SPECIES_CALYREX_SHADOW                          1233
#define SPECIES_BASCULEGION_F                           1234
#define SPECIES_ALCREMIE_BERRY                          SPECIES_ALCREMIE_BERRY_VANILLA_CREAM
#define SPECIES_ALCREMIE_BERRY_VANILLA_CREAM            1235
#define SPECIES_ALCREMIE_BERRY_RUBY_CREAM               1236
#define SPECIES_ALCREMIE_BERRY_MATCHA_CREAM             1237
#define SPECIES_ALCREMIE_BERRY_MINT_CREAM               1238
#define SPECIES_ALCREMIE_BERRY_LEMON_CREAM              1239
#define SPECIES_ALCREMIE_BERRY_SALTED_CREAM             1240
#define SPECIES_ALCREMIE_BERRY_RUBY_SWIRL               1241
#define SPECIES_ALCREMIE_BERRY_CARAMEL_SWIRL            1242
#define SPECIES_ALCREMIE_BERRY_RAINBOW_SWIRL            1243
#define SPECIES_ALCREMIE_LOVE                           SPECIES_ALCREMIE_LOVE_VANILLA_CREAM
#define SPECIES_ALCREMIE_LOVE_VANILLA_CREAM             1244
#define SPECIES_ALCREMIE_LOVE_RUBY_CREAM                1245
#define SPECIES_ALCREMIE_LOVE_MATCHA_CREAM              1246
#define SPECIES_ALCREMIE_LOVE_MINT_CREAM                1247
#define SPECIES_ALCREMIE_LOVE_LEMON_CREAM               1248
#define SPECIES_ALCREMIE_LOVE_SALTED_CREAM              1249
#define SPECIES_ALCREMIE_LOVE_RUBY_SWIRL                1250
#define SPECIES_ALCREMIE_LOVE_CARAMEL_SWIRL             1251
#define SPECIES_ALCREMIE_LOVE_RAINBOW_SWIRL             1252
#define SPECIES_ALCREMIE_STAR                           SPECIES_ALCREMIE_STAR_VANILLA_CREAM
#define SPECIES_ALCREMIE_STAR_VANILLA_CREAM             1253
#define SPECIES_ALCREMIE_STAR_RUBY_CREAM                1254
#define SPECIES_ALCREMIE_STAR_MATCHA_CREAM              1255
#define SPECIES_ALCREMIE_STAR_MINT_CREAM                1256
#define SPECIES_ALCREMIE_STAR_LEMON_CREAM               1257
#define SPECIES_ALCREMIE_STAR_SALTED_CREAM              1258
#define SPECIES_ALCREMIE_STAR_RUBY_SWIRL                1259
#define SPECIES_ALCREMIE_STAR_CARAMEL_SWIRL             1260
#define SPECIES_ALCREMIE_STAR_RAINBOW_SWIRL             1261
#define SPECIES_ALCREMIE_CLOVER                         SPECIES_ALCREMIE_CLOVER_VANILLA_CREAM
#define SPECIES_ALCREMIE_CLOVER_VANILLA_CREAM           1262
#define SPECIES_ALCREMIE_CLOVER_RUBY_CREAM              1263
#define SPECIES_ALCREMIE_CLOVER_MATCHA_CREAM            1264
#define SPECIES_ALCREMIE_CLOVER_MINT_CREAM              1265
#define SPECIES_ALCREMIE_CLOVER_LEMON_CREAM             1266
#define SPECIES_ALCREMIE_CLOVER_SALTED_CREAM            1267
#define SPECIES_ALCREMIE_CLOVER_RUBY_SWIRL              1268
#define SPECIES_ALCREMIE_CLOVER_CARAMEL_SWIRL           1269
#define SPECIES_ALCREMIE_CLOVER_RAINBOW_SWIRL           1270
#define SPECIES_ALCREMIE_FLOWER                         SPECIES_ALCREMIE_FLOWER_VANILLA_CREAM
#define SPECIES_ALCREMIE_FLOWER_VANILLA_CREAM           1271
#define SPECIES_ALCREMIE_FLOWER_RUBY_CREAM              1272
#define SPECIES_ALCREMIE_FLOWER_MATCHA_CREAM            1273
#define SPECIES_ALCREMIE_FLOWER_MINT_CREAM              1274
#define SPECIES_ALCREMIE_FLOWER_LEMON_CREAM             1275
#define SPECIES_ALCREMIE_FLOWER_SALTED_CREAM            1276
#define SPECIES_ALCREMIE_FLOWER_RUBY_SWIRL              1277
#define SPECIES_ALCREMIE_FLOWER_CARAMEL_SWIRL           1278
#define SPECIES_ALCREMIE_FLOWER_RAINBOW_SWIRL           1279
#define SPECIES_ALCREMIE_RIBBON                         SPECIES_ALCREMIE_RIBBON_VANILLA_CREAM
#define SPECIES_ALCREMIE_RIBBON_VANILLA_CREAM           1280
#define SPECIES_ALCREMIE_RIBBON_RUBY_CREAM              1281
#define SPECIES_ALCREMIE_RIBBON_MATCHA_CREAM            1282
#define SPECIES_ALCREMIE_RIBBON_MINT_CREAM              1283
#define SPECIES_ALCREMIE_RIBBON_LEMON_CREAM             1284
#define SPECIES_ALCREMIE_RIBBON_SALTED_CREAM            1285
#define SPECIES_ALCREMIE_RIBBON_RUBY_SWIRL              1286
#define SPECIES_ALCREMIE_RIBBON_CARAMEL_SWIRL           1287
#define SPECIES_ALCREMIE_RIBBON_RAINBOW_SWIRL           1288

#define GEN9_START                                      SPECIES_ALCREMIE_RIBBON_RAINBOW_SWIRL

#define SPECIES_SPRIGATITO                              1289
#define SPECIES_FLORAGATO                               1290
#define SPECIES_MEOWSCARADA                             1291
#define SPECIES_FUECOCO                                 1292
#define SPECIES_CROCALOR                                1293
#define SPECIES_SKELEDIRGE                              1294
#define SPECIES_QUAXLY                                  1295
#define SPECIES_QUAXWELL                                1296
#define SPECIES_QUAQUAVAL                               1297
#define SPECIES_LECHONK                                 1298
#define SPECIES_OINKOLOGNE                              SPECIES_OINKOLOGNE_M
#define SPECIES_OINKOLOGNE_M                            1299
#define SPECIES_OINKOLOGNE_F                            1300
#define SPECIES_TAROUNTULA                              1301
#define SPECIES_SPIDOPS                                 1302
#define SPECIES_NYMBLE                                  1303
#define SPECIES_LOKIX                                   1304
#define SPECIES_PAWMI                                   1305
#define SPECIES_PAWMO                                   1306
#define SPECIES_PAWMOT                                  1307
#define SPECIES_TANDEMAUS                               1308
#define SPECIES_MAUSHOLD                                SPECIES_MAUSHOLD_THREE
#define SPECIES_MAUSHOLD_THREE                          1309
#define SPECIES_MAUSHOLD_FOUR                           1310
#define SPECIES_FIDOUGH                                 1311
#define SPECIES_DACHSBUN                                1312
#define SPECIES_SMOLIV                                  1313
#define SPECIES_DOLLIV                                  1314
#define SPECIES_ARBOLIVA                                1315
#define SPECIES_SQUAWKABILLY                            SPECIES_SQUAWKABILLY_GREEN
#define SPECIES_SQUAWKABILLY_GREEN                      1316
#define SPECIES_SQUAWKABILLY_BLUE                       1317
#define SPECIES_SQUAWKABILLY_YELLOW                     1318
#define SPECIES_SQUAWKABILLY_WHITE                      1319
#define SPECIES_NACLI                                   1320
#define SPECIES_NACLSTACK                               1321
#define SPECIES_GARGANACL                               1322
#define SPECIES_CHARCADET                               1323
#define SPECIES_ARMAROUGE                               1324
#define SPECIES_CERULEDGE                               1325
#define SPECIES_TADBULB                                 1326
#define SPECIES_BELLIBOLT                               1327
#define SPECIES_WATTREL                                 1328
#define SPECIES_KILOWATTREL                             1329
#define SPECIES_MASCHIFF                                1330
#define SPECIES_MABOSSTIFF                              1331
#define SPECIES_SHROODLE                                1332
#define SPECIES_GRAFAIAI                                1333
#define SPECIES_BRAMBLIN                                1334
#define SPECIES_BRAMBLEGHAST                            1335
#define SPECIES_TOEDSCOOL                               1336
#define SPECIES_TOEDSCRUEL                              1337
#define SPECIES_KLAWF                                   1338
#define SPECIES_CAPSAKID                                1339
#define SPECIES_SCOVILLAIN                              1340
#define SPECIES_RELLOR                                  1341
#define SPECIES_RABSCA                                  1342
#define SPECIES_FLITTLE                                 1343
#define SPECIES_ESPATHRA                                1344
#define SPECIES_TINKATINK                               1345
#define SPECIES_TINKATUFF                               1346
#define SPECIES_TINKATON                                1347
#define SPECIES_WIGLETT                                 1348
#define SPECIES_WUGTRIO                                 1349
#define SPECIES_BOMBIRDIER                              1350
#define SPECIES_FINIZEN                                 1351
#define SPECIES_PALAFIN                                 SPECIES_PALAFIN_ZERO
#define SPECIES_PALAFIN_ZERO                            1352
#define SPECIES_PALAFIN_HERO                            1353
#define SPECIES_VAROOM                                  1354
#define SPECIES_REVAVROOM                               1355
#define SPECIES_CYCLIZAR                                1356
#define SPECIES_ORTHWORM                                1357
#define SPECIES_GLIMMET                                 1358
#define SPECIES_GLIMMORA                                1359
#define SPECIES_GREAVARD                                1360
#define SPECIES_HOUNDSTONE                              1361
#define SPECIES_FLAMIGO                                 1362
#define SPECIES_CETODDLE                                1363
#define SPECIES_CETITAN                                 1364
#define SPECIES_VELUZA                                  1365
#define SPECIES_DONDOZO                                 1366
#define SPECIES_TATSUGIRI                               SPECIES_TATSUGIRI_CURLY
#define SPECIES_TATSUGIRI_CURLY                         1367
#define SPECIES_TATSUGIRI_DROOPY                        1368
#define SPECIES_TATSUGIRI_STRETCHY                      1369
#define SPECIES_ANNIHILAPE                              1370
#define SPECIES_CLODSIRE                                1371
#define SPECIES_FARIGIRAF                               1372
#define SPECIES_DUDUNSPARCE                             SPECIES_DUDUNSPARCE_TWO_SEGMENT
#define SPECIES_DUDUNSPARCE_TWO_SEGMENT                 1373
#define SPECIES_DUDUNSPARCE_THREE_SEGMENT               1374
#define SPECIES_KINGAMBIT                               1375
#define SPECIES_GREAT_TUSK                              1376
#define SPECIES_SCREAM_TAIL                             1377
#define SPECIES_BRUTE_BONNET                            1378
#define SPECIES_FLUTTER_MANE                            1379
#define SPECIES_SLITHER_WING                            1380
#define SPECIES_SANDY_SHOCKS                            1381
#define SPECIES_IRON_TREADS                             1382
#define SPECIES_IRON_BUNDLE                             1383
#define SPECIES_IRON_HANDS                              1384
#define SPECIES_IRON_JUGULIS                            1385
#define SPECIES_IRON_MOTH                               1386
#define SPECIES_IRON_THORNS                             1387
#define SPECIES_FRIGIBAX                                1388
#define SPECIES_ARCTIBAX                                1389
#define SPECIES_BAXCALIBUR                              1390
#define SPECIES_GIMMIGHOUL                              SPECIES_GIMMIGHOUL_CHEST
#define SPECIES_GIMMIGHOUL_CHEST                        1391
#define SPECIES_GIMMIGHOUL_ROAMING                      1392
#define SPECIES_GHOLDENGO                               1393
#define SPECIES_WO_CHIEN                                1394
#define SPECIES_CHIEN_PAO                               1395
#define SPECIES_TING_LU                                 1396
#define SPECIES_CHI_YU                                  1397
#define SPECIES_ROARING_MOON                            1398
#define SPECIES_IRON_VALIANT                            1399
#define SPECIES_KORAIDON                                1400
#define SPECIES_MIRAIDON                                1401
// Paldean Forms
#define SPECIES_TAUROS_PALDEA_COMBAT                    1402
#define SPECIES_TAUROS_PALDEA_BLAZE                     1403
#define SPECIES_TAUROS_PALDEA_AQUA                      1404
#define SPECIES_WOOPER_PALDEA                           1405
// Scarlet and Violet 1.2.0
#define SPECIES_WALKING_WAKE                            1406
#define SPECIES_IRON_LEAVES                             1407
// Teal Mask
#define SPECIES_DIPPLIN                                 1408
#define SPECIES_POLTCHAGEIST                            SPECIES_POLTCHAGEIST_COUNTERFEIT
#define SPECIES_POLTCHAGEIST_COUNTERFEIT                1409
#define SPECIES_POLTCHAGEIST_ARTISAN                    1410
#define SPECIES_SINISTCHA                               SPECIES_SINISTCHA_UNREMARKABLE
#define SPECIES_SINISTCHA_UNREMARKABLE                  1411
#define SPECIES_SINISTCHA_MASTERPIECE                   1412
#define SPECIES_OKIDOGI                                 1413
#define SPECIES_MUNKIDORI                               1414
#define SPECIES_FEZANDIPITI                             1415
#define SPECIES_OGERPON                                 SPECIES_OGERPON_TEAL
#define SPECIES_OGERPON_TEAL                            1416
#define SPECIES_OGERPON_WELLSPRING                      1417
#define SPECIES_OGERPON_HEARTHFLAME                     1418
#define SPECIES_OGERPON_CORNERSTONE                     1419
#define SPECIES_OGERPON_TEAL_TERA                       1420
#define SPECIES_OGERPON_WELLSPRING_TERA                 1421
#define SPECIES_OGERPON_HEARTHFLAME_TERA                1422
#define SPECIES_OGERPON_CORNERSTONE_TERA                1423
#define SPECIES_URSALUNA_BLOODMOON                      1424
// Indigo Disk
#define SPECIES_ARCHALUDON                              1425
#define SPECIES_HYDRAPPLE                               1426
#define SPECIES_GOUGING_FIRE                            1427
#define SPECIES_RAGING_BOLT                             1428
#define SPECIES_IRON_BOULDER                            1429
#define SPECIES_IRON_CROWN                              1430
#define SPECIES_TERAPAGOS                               SPECIES_TERAPAGOS_NORMAL
#define SPECIES_TERAPAGOS_NORMAL                        1431
#define SPECIES_TERAPAGOS_TERASTAL                      1432
#define SPECIES_TERAPAGOS_STELLAR                       1433
#define SPECIES_PECHARUNT                               1434
#define SPECIES_LUGIA_SHADOW                            1435
#define SPECIES_MOTHIM_SANDY                            1436
#define SPECIES_MOTHIM_TRASH                            1437
#define SPECIES_SCATTERBUG_POLAR                        1438
#define SPECIES_SCATTERBUG_TUNDRA                       1439
#define SPECIES_SCATTERBUG_CONTINENTAL                  1440
#define SPECIES_SCATTERBUG_GARDEN                       1441
#define SPECIES_SCATTERBUG_ELEGANT                      1442
#define SPECIES_SCATTERBUG_MEADOW                       1443
#define SPECIES_SCATTERBUG_MODERN                       1444
#define SPECIES_SCATTERBUG_MARINE                       1445
#define SPECIES_SCATTERBUG_ARCHIPELAGO                  1446
#define SPECIES_SCATTERBUG_HIGH_PLAINS                  1447
#define SPECIES_SCATTERBUG_SANDSTORM                    1448
#define SPECIES_SCATTERBUG_RIVER                        1449
#define SPECIES_SCATTERBUG_MONSOON                      1450
#define SPECIES_SCATTERBUG_SAVANNA                      1451
#define SPECIES_SCATTERBUG_SUN                          1452
#define SPECIES_SCATTERBUG_OCEAN                        1453
#define SPECIES_SCATTERBUG_JUNGLE                       1454
#define SPECIES_SCATTERBUG_FANCY                        1455
#define SPECIES_SCATTERBUG_POKEBALL                     1456
#define SPECIES_SPEWPA_POLAR                            1457
#define SPECIES_SPEWPA_TUNDRA                           1458
#define SPECIES_SPEWPA_CONTINENTAL                      1459
#define SPECIES_SPEWPA_GARDEN                           1460
#define SPECIES_SPEWPA_ELEGANT                          1461
#define SPECIES_SPEWPA_MEADOW                           1462
#define SPECIES_SPEWPA_MODERN                           1463
#define SPECIES_SPEWPA_MARINE                           1464
#define SPECIES_SPEWPA_ARCHIPELAGO                      1465
#define SPECIES_SPEWPA_HIGH_PLAINS                      1466
#define SPECIES_SPEWPA_SANDSTORM                        1467
#define SPECIES_SPEWPA_RIVER                            1468
#define SPECIES_SPEWPA_MONSOON                          1469
#define SPECIES_SPEWPA_SAVANNA                          1470
#define SPECIES_SPEWPA_SUN                              1471
#define SPECIES_SPEWPA_OCEAN                            1472
#define SPECIES_SPEWPA_JUNGLE                           1473
#define SPECIES_SPEWPA_FANCY                            1474
#define SPECIES_SPEWPA_POKEBALL                         1475
#define SPECIES_RATICATE_ALOLA_TOTEM                    1476
#define SPECIES_GUMSHOOS_TOTEM                          1477
#define SPECIES_VIKAVOLT_TOTEM                          1478
#define SPECIES_LURANTIS_TOTEM                          1479
#define SPECIES_SALAZZLE_TOTEM                          1480
#define SPECIES_MIMIKYU_TOTEM                           SPECIES_MIMIKYU_TOTEM_DISGUISED
#define SPECIES_MIMIKYU_TOTEM_DISGUISED                 1481
#define SPECIES_KOMMO_O_TOTEM                           1482
#define SPECIES_MAROWAK_ALOLA_TOTEM                     1483
#define SPECIES_RIBOMBEE_TOTEM                          1484
#define SPECIES_ARAQUANID_TOTEM                         1485
#define SPECIES_TOGEDEMARU_TOTEM                        1486
#define SPECIES_PIKACHU_STARTER                         1487
#define SPECIES_EEVEE_STARTER                           1488
#define SPECIES_VENUSAUR_GMAX                           1489
#define SPECIES_BLASTOISE_GMAX                          1490
#define SPECIES_CHARIZARD_GMAX                          1491
#define SPECIES_BUTTERFREE_GMAX                         1492
#define SPECIES_PIKACHU_GMAX                            1493
#define SPECIES_MEOWTH_GMAX                             1494
#define SPECIES_MACHAMP_GMAX                            1495
#define SPECIES_GENGAR_GMAX                             1496
#define SPECIES_KINGLER_GMAX                            1497
#define SPECIES_LAPRAS_GMAX                             1498
#define SPECIES_EEVEE_GMAX                              1499
#define SPECIES_SNORLAX_GMAX                            1500
#define SPECIES_GARBODOR_GMAX                           1501
#define SPECIES_MELMETAL_GMAX                           1502
#define SPECIES_RILLABOOM_GMAX                          1503
#define SPECIES_CINDERACE_GMAX                          1504
#define SPECIES_INTELEON_GMAX                           1505
#define SPECIES_CORVIKNIGHT_GMAX                        1506
#define SPECIES_ORBEETLE_GMAX                           1507
#define SPECIES_DREDNAW_GMAX                            1508
#define SPECIES_COALOSSAL_GMAX                          1509
#define SPECIES_FLAPPLE_GMAX                            1510
#define SPECIES_APPLETUN_GMAX                           1511
#define SPECIES_SANDACONDA_GMAX                         1512
#define SPECIES_TOXTRICITY_AMPED_GMAX                   1513
#define SPECIES_TOXTRICITY_LOW_KEY_GMAX                 1514
#define SPECIES_CENTISKORCH_GMAX                        1515
#define SPECIES_HATTERENE_GMAX                          1516
#define SPECIES_GRIMMSNARL_GMAX                         1517
#define SPECIES_ALCREMIE_GMAX                           1518
#define SPECIES_COPPERAJAH_GMAX                         1519
#define SPECIES_DURALUDON_GMAX                          1520
#define SPECIES_URSHIFU_SINGLE_STRIKE_GMAX              1521
#define SPECIES_URSHIFU_GMAX                            SPECIES_URSHIFU_SINGLE_STRIKE_GMAX
#define SPECIES_URSHIFU_SINGLE_STRIKE_STYLE_GMAX        SPECIES_URSHIFU_SINGLE_STRIKE_GMAX
#define SPECIES_URSHIFU_RAPID_STRIKE_GMAX               1522
#define SPECIES_URSHIFU_RAPID_STRIKE_STYLE_GMAX         SPECIES_URSHIFU_RAPID_STRIKE_GMAX
#define SPECIES_MIMIKYU_BUSTED_TOTEM                    1523
#define SPECIES_MIMIKYU_TOTEM_BUSTED                    SPECIES_MIMIKYU_BUSTED_TOTEM
#define SPECIES_TORTERRA_MEGA                           1524
#define SPECIES_TYPHLOSION_MEGA                         1525
#define SPECIES_FERALIGATR_MEGA                         1526
#define SPECIES_INFERNAPE_MEGA                          1527
#define SPECIES_LUXRAY_MEGA                             1528
#define SPECIES_FLYGON_MEGA                             1529
#define SPECIES_MILOTIC_MEGA                            1530
#define SPECIES_BUTTERFREE_MEGA                         1531
#define SPECIES_CROBAT_MEGA                             1532
#define SPECIES_DRAGONITE_MEGA                          1533
#define SPECIES_EMPOLEON_MEGA                           1534
#define SPECIES_LAPRAS_MEGA                             1535
#define SPECIES_MACHAMP_MEGA                            1536
#define SPECIES_MEGANIUM_MEGA                           1537
#define SPECIES_NIDOKING_MEGA                           1538
#define SPECIES_NIDOQUEEN_MEGA                          1539
#define SPECIES_SHEDINJA_MEGA                           1540
#define SPECIES_ELECTIVIRE_MEGA                         1541
#define SPECIES_FROSLASS_MEGA                           1542
#define SPECIES_HAXORUS_MEGA                            1543
#define SPECIES_MAGMORTAR_MEGA                          1544
#define SPECIES_RAPIDASH_MEGA                           1545
#define SPECIES_STARMIE_MEGA                            1546
#define SPECIES_MIGHTYENA_MEGA                          1547
#define SPECIES_GRENINJA_MEGA                           1548
#define SPECIES_ARBOK_MEGA                              1549
#define SPECIES_ARCANINE_MEGA                           1550
#define SPECIES_KINGDRA_MEGA                            1551
#define SPECIES_TYPHLOSION_MEGA_H                       1552
#define SPECIES_GENGAR_MEGA_Y                           1553
#define SPECIES_QUAGSIRE_MEGA                           1554
#define SPECIES_MAGNEZONE_MEGA                          1555
#define SPECIES_WEAVILE_MEGA                            1556
#define SPECIES_ROSERADE_MEGA                           1557
#define SPECIES_KYUREM_B_MEGA                             1558
#define SPECIES_KYUREM_W_MEGA                             1559


#define SPECIES_EGG                                     (SPECIES_KYUREM_W_MEGA + 1)
>>>>>>> Stashed changes

#define NUM_SPECIES SPECIES_EGG

#define SPECIES_UNOWN_B (NUM_SPECIES + 1)
#define SPECIES_UNOWN_C (SPECIES_UNOWN_B + 1)
#define SPECIES_UNOWN_D (SPECIES_UNOWN_B + 2)
#define SPECIES_UNOWN_E (SPECIES_UNOWN_B + 3)
#define SPECIES_UNOWN_F (SPECIES_UNOWN_B + 4)
#define SPECIES_UNOWN_G (SPECIES_UNOWN_B + 5)
#define SPECIES_UNOWN_H (SPECIES_UNOWN_B + 6)
#define SPECIES_UNOWN_I (SPECIES_UNOWN_B + 7)
#define SPECIES_UNOWN_J (SPECIES_UNOWN_B + 8)
#define SPECIES_UNOWN_K (SPECIES_UNOWN_B + 9)
#define SPECIES_UNOWN_L (SPECIES_UNOWN_B + 10)
#define SPECIES_UNOWN_M (SPECIES_UNOWN_B + 11)
#define SPECIES_UNOWN_N (SPECIES_UNOWN_B + 12)
#define SPECIES_UNOWN_O (SPECIES_UNOWN_B + 13)
#define SPECIES_UNOWN_P (SPECIES_UNOWN_B + 14)
#define SPECIES_UNOWN_Q (SPECIES_UNOWN_B + 15)
#define SPECIES_UNOWN_R (SPECIES_UNOWN_B + 16)
#define SPECIES_UNOWN_S (SPECIES_UNOWN_B + 17)
#define SPECIES_UNOWN_T (SPECIES_UNOWN_B + 18)
#define SPECIES_UNOWN_U (SPECIES_UNOWN_B + 19)
#define SPECIES_UNOWN_V (SPECIES_UNOWN_B + 20)
#define SPECIES_UNOWN_W (SPECIES_UNOWN_B + 21)
#define SPECIES_UNOWN_X (SPECIES_UNOWN_B + 22)
#define SPECIES_UNOWN_Y (SPECIES_UNOWN_B + 23)
#define SPECIES_UNOWN_Z (SPECIES_UNOWN_B + 24)
#define SPECIES_UNOWN_EMARK (SPECIES_UNOWN_B + 25)
#define SPECIES_UNOWN_QMARK (SPECIES_UNOWN_B + 26)

#endif  // GUARD_CONSTANTS_SPECIES_H
